<?php

/**
 * Maps SII XSD elements to builder array keys.
 *
 * The ONLY hand-maintained file of the rules generator. When the generator meets an XSD element missing here, it fails loudly listing the element.
 *
 * Shape: [section => [xsdElement => builderKey|'key.*.subkey'|null]]
 *
 * A null value skips the element (not exposed through builders).
 *
 * @see dev/generate-rules.php
 */
return [
    'ISSUER' => [
        'RUTEmisor' => 'rut',
        'RznSoc' => 'name',
        'GiroEmis' => 'activity',
        'Acteco' => 'activity_code',
        'Telefono' => 'telephone',
        'CorreoEmisor' => 'email',
        'Sucursal' => 'branch',
        'DirOrigen' => 'address',
        'CmnaOrigen' => 'commune',
        'CiudadOrigen' => 'city',
        'CdgSIISucur' => null,
        'GuiaExport' => null,
        'CdgVendedor' => null,
        'IdAdicEmisor' => null,
        'RUTProveedor' => null,
        'RznSocProveedor' => null,
    ],
    'RECEIVER' => [
        'RUTRecep' => 'rut',
        'RznSocRecep' => 'name',
        'GiroRecep' => 'activity',
        'Contacto' => null,
        'CorreoRecep' => 'email',
        'DirRecep' => 'address',
        'CmnaRecep' => 'commune',
        'CiudadRecep' => 'city',
        'DirPostal' => null,
        'CmnaPostal' => null,
        'CiudadPostal' => null,
        'CdgIntRecep' => null,
        'Extranjero' => null,
    ],
    'ITEM' => [
        'NmbItem' => 'name',
        'DscItem' => 'description',
        'QtyItem' => 'quantity',
        'UnmdItem' => 'unit',
        'PrcItem' => 'unit_price',
        'DescuentoPct' => 'discount_percentage',
        'DescuentoMonto' => 'discount_amount',
        'IndExe' => 'exempt',
        'CodImpAdic' => 'taxes',
        'QtyRef' => null,
        'UnmdRef' => null,
        'PrcRef' => null,
        'Subcantidad' => null,
        'FchElabor' => null,
        'FchVencim' => null,
        'OtrMnda' => null,
        'SubDscto' => null,
        'RecargoPct' => null,
        'RecargoMonto' => null,
        'SubRecargo' => null,
        'TpoCodigo' => 'code_type',
        'VlrCodigo' => 'code',
        'NroLinDet' => null,
        'MontoItem' => null,
        'Retenedor' => null,
    ],
    'REFERENCE' => [
        'TpoDocRef' => 'document_type',
        'FolioRef' => 'folio',
        'FchRef' => 'date',
        'CodRef' => 'reference_code',
        'RazonRef' => 'reason',
        'NroLinRef' => null,
        'IndGlobal' => null,
        'RUTOtr' => null,
    ],
    'GLOBAL_MODIFIER' => [
        'TpoMov' => 'type',
        'GlosaDR' => 'description',
        'TpoValor' => 'value_type',
        'ValorDR' => 'value',
        'ValorDROtrMnda' => null,
        'IndExeDR' => 'target',
        'NroLinDR' => null,
    ],
    'PAYMENT_TERM' => [
        'FmaPago' => 'condition',
        'FchVenc' => 'expiration_date',
        'FchCancel' => null,
        'MntCancel' => null,
        'SaldoInsol' => null,
        'MntPagos' => null,
        'PeriodoDesde' => null,
        'PeriodoHasta' => null,
        'MedioPago' => null,
        'TpoCtaPago' => null,
        'NumCtaPago' => null,
        'BcoPago' => null,
        'TermPagoCdg' => null,
        'TermPagoGlosa' => null,
        'TermPagoDias' => null,
    ],
    'TRANSPORT' => [
        'Patente' => 'vehicle_plate',
        'PatenteCarro' => 'trailer_plate',
        'RUTTrans' => 'carrier_rut',
        'RUTChofer' => 'driver_rut',
        'NombreChofer' => 'driver_name',
        'DirDest' => 'destination_address',
        'CmnaDest' => 'destination_commune',
        'CiudadDest' => 'destination_city',
        'FchSalida' => 'departure_at',
        'FchLlegada' => 'arrival_at',
        'Chofer' => null,
        'Aduana' => null,
        'HraSalida' => null,
    ],
    'TOTALS' => [
        'MntNeto' => 'net',
        'MntExe' => 'exempt',
        'IVA' => 'tax',
        'MntTotal' => 'total',
        'MontoNF' => 'non_billable',
        'MntBase' => null,
        'MntMargenCom' => null,
        'TasaIVA' => null,
        'IVAProp' => null,
        'IVATerc' => null,
        'ImptoReten' => null,
        'IVANoRet' => null,
        'CredEC' => null,
        'GrntDep' => null,
        'Comisiones' => null,
        'MontoPeriodo' => null,
        'SaldoAnterior' => null,
        'VlrPagar' => null,
    ],
    'DOCUMENT' => [
        'TipoDTE' => 'document_type',
        'Folio' => 'folio',
        'FchEmis' => 'issued_on',
        'IndNoRebaja' => 'non_rebillable',
        'TipoDespacho' => 'tipo_despacho',
        'IndTraslado' => 'ind_traslado',
        'IndServicio' => null,
        'MntBruto' => null,
        'TpoTranCompra' => null,
        'TpoTranVenta' => null,
        'FmaPagExp' => null,
        'TpoImpresion' => null,
        'MntPagos' => null,
        'PeriodoDesde' => null,
        'PeriodoHasta' => null,
        'MedioPago' => null,
        'TpoCtaPago' => null,
        'NumCtaPago' => null,
        'BcoPago' => null,
        'TermPagoCdg' => null,
        'TermPagoGlosa' => null,
        'TermPagoDias' => null,
        'TipoFactEsp' => null,
        'TpoTranCompra' => null,
        'TpoTranVenta' => null,
    ],
];
